name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@40bbd0f4d912b24d4d3047299b6b5900f349e6da # v0.3.0
        id: build
        with:
          auto-install: true
      - run: |
          moon --color --log trace ci docs:build
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
      - uses: "moonrepo/run-report-action@d00ab311fde5366a4a5194afae6e87e7c4b0704c" # v1.5.1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cloudflare/wrangler-action@a8be0ea72a399752dd2735fa16ea0d424f2335ca # v3.4.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.18.0"
          workingDirectory: "apps/docs"
          command: pages deploy dist --project-name astropix-docs
