name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@0e0303e01e1006eb33278709d47292908525f24c # v0.2.1
        id: build
        with:
          auto-install: true
      - run: |
          moon --color --log trace ci docs:build
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
      - uses: "moonrepo/run-report-action@d00ab311fde5366a4a5194afae6e87e7c4b0704c" # v1.5.1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cloudflare/wrangler-action@5e8484995321734668f14981c316aa9188d76ed1 # v3.3.2
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.18.0"
          workingDirectory: "apps/docs"
          command: pages deploy dist --project-name astropix-docs
