name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@a58facee196d41231c97018b7348faf2f0d62aef # v0.2.0
        with:
          auto-install: true
      - run: "moon ci docs:build"
      - uses: cloudflare/wrangler-action@5e8484995321734668f14981c316aa9188d76ed1 # v3.3.2
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.18.0"
          workingDirectory: "apps/docs"
          command: pages deploy dist --project-name astropix-docs
