name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0, 1]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0.2.0
        with:
          auto-install: true
      - run: "moon ci docs:build --job ${{ matrix.index }} --jobTotal 2"
      - uses: cloudflare/wrangler-action@v3.3.2
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "3.18.0"
          workingDirectory: "apps/docs"
          command: pages deploy dist --project-name astropix-docs
